[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "snipeit-api"
version = "0.1.0"
description = "A Python client for the Snipe-IT API"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests",
    "urllib3",
]

[project.urls]
"Homepage" = "https://github.com/gemini/inventory-library"

[project.optional-dependencies]
dev = [
    "requests-mock",
    "pytest",
    "pytest-cov",
    "coverage",
    "hypothesis",
    "mutmut<3",
]
